filebeat.inputs:
  - type: filestream
    id: docker-logs
    enabled: true

    paths:
      - /var/lib/docker/containers/*/*.log

    parsers:
      - container:
          stream: all
          format: docker

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

setup.kibana:
  host: "http://kibana:5601"

setup.template.enabled: true
setup.template.name: "logs-content-hub"
setup.template.pattern: "logs-content-hub-*"

setup.template.settings:
  index.number_of_shards: 1

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "logs-content-hub-%{+yyyy.MM.dd}"

logging.level: info